language: ruby

before_install:
  - mkdir travis-phantomjs
  - wget https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -O $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2
  - tar -xvf $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -C $PWD/travis-phantomjs
  - export PATH=$PWD/travis-phantomjs:$PATH
  - npm install

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2

sudo: false

script:
 - bundle exec rake test
 - script/test

gemfile:
  - Gemfile.rails32
  - Gemfile.rails40
  - Gemfile.rails41
  - Gemfile.rails42

